INSERT INTO permission (permission_id, permission) VALUES
(1, 'READ_PROFILE'),
(2, 'READ_SKILL'),
(3, 'READ_QUESTION'),
(4, 'CREATE_QUESTION'),
(5, 'UPDATE_QUESTION'),
(6, 'READ_USER'),
(7, 'CREATE_USER'),
(8, 'UPDATE_USER'),
-- ('DELETE_USER'),
(9, 'READ_PERMISSION'),
(10, 'GRANT_PERMISSION'),
(11, 'REVOKE_PERMISSION'),
(12, 'READ_EXAM'),
(13, 'CREATE_EXAM_RANDOM'),
(14, 'CREATE_EXAM_CUSTOM'),
-- ('CREATE_EXAM'),
(15, 'DELETE_EXAM'),
(16, 'DO_EXAM');


 

